server:
  port: 8081
    
spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: "your database password"
    url: jdbc:mysql://localhost:3306/jrtp
    username: "your database name"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true